name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 安装 pnpm（不用 npm 安装，避免429）
      - uses: pnpm/action-setup@v4
        with:
          version: 10 # 指定你项目用的 pnpm 版本

      # 缓存依赖，加速构建
      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run docs:build
        timeout-minutes: 30
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          token: ${{ secrets.PATC_TOKEN }}
          branch: gh-pages
          folder: docs/dist/client
          force: true
          commit-message: website deploy
          repository-name: EralChen/vunk-markdown

      - name: Cleanup
        run: rm -rf docs/dist
